/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TenantRouteImport } from './routes/_tenant'
import { Route as CentralRouteImport } from './routes/_central'
import { Route as CentralIndexRouteImport } from './routes/_central/index'
import { Route as TenantLoginRouteImport } from './routes/_tenant/login'
import { Route as TenantAdminRouteImport } from './routes/_tenant/admin'
import { Route as TenantAdminTablesRouteImport } from './routes/_tenant/admin/tables'
import { Route as TenantAdminStaffRouteImport } from './routes/_tenant/admin/staff'
import { Route as TenantAdminSettingsRouteImport } from './routes/_tenant/admin/settings'
import { Route as TenantAdminRestaurantsRouteImport } from './routes/_tenant/admin/restaurants'
import { Route as TenantAdminOrdersRouteImport } from './routes/_tenant/admin/orders'
import { Route as TenantAdminDashboardRouteImport } from './routes/_tenant/admin/dashboard'
import { Route as TenantAdminMenuIndexRouteImport } from './routes/_tenant/admin/menu/index'
import { Route as TenantAdminMenuItemsRouteImport } from './routes/_tenant/admin/menu/items'

const TenantRoute = TenantRouteImport.update({
  id: '/_tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralRoute = CentralRouteImport.update({
  id: '/_central',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralIndexRoute = CentralIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CentralRoute,
} as any)
const TenantLoginRoute = TenantLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => TenantRoute,
} as any)
const TenantAdminRoute = TenantAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => TenantRoute,
} as any)
const TenantAdminTablesRoute = TenantAdminTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => TenantAdminRoute,
} as any)
const TenantAdminStaffRoute = TenantAdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => TenantAdminRoute,
} as any)
const TenantAdminSettingsRoute = TenantAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TenantAdminRoute,
} as any)
const TenantAdminRestaurantsRoute = TenantAdminRestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => TenantAdminRoute,
} as any)
const TenantAdminOrdersRoute = TenantAdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => TenantAdminRoute,
} as any)
const TenantAdminDashboardRoute = TenantAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => TenantAdminRoute,
} as any)
const TenantAdminMenuIndexRoute = TenantAdminMenuIndexRouteImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => TenantAdminRoute,
} as any)
const TenantAdminMenuItemsRoute = TenantAdminMenuItemsRouteImport.update({
  id: '/menu/items',
  path: '/menu/items',
  getParentRoute: () => TenantAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof TenantAdminRouteWithChildren
  '/login': typeof TenantLoginRoute
  '/': typeof CentralIndexRoute
  '/admin/dashboard': typeof TenantAdminDashboardRoute
  '/admin/orders': typeof TenantAdminOrdersRoute
  '/admin/restaurants': typeof TenantAdminRestaurantsRoute
  '/admin/settings': typeof TenantAdminSettingsRoute
  '/admin/staff': typeof TenantAdminStaffRoute
  '/admin/tables': typeof TenantAdminTablesRoute
  '/admin/menu/items': typeof TenantAdminMenuItemsRoute
  '/admin/menu': typeof TenantAdminMenuIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof TenantAdminRouteWithChildren
  '/login': typeof TenantLoginRoute
  '/': typeof CentralIndexRoute
  '/admin/dashboard': typeof TenantAdminDashboardRoute
  '/admin/orders': typeof TenantAdminOrdersRoute
  '/admin/restaurants': typeof TenantAdminRestaurantsRoute
  '/admin/settings': typeof TenantAdminSettingsRoute
  '/admin/staff': typeof TenantAdminStaffRoute
  '/admin/tables': typeof TenantAdminTablesRoute
  '/admin/menu/items': typeof TenantAdminMenuItemsRoute
  '/admin/menu': typeof TenantAdminMenuIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_central': typeof CentralRouteWithChildren
  '/_tenant': typeof TenantRouteWithChildren
  '/_tenant/admin': typeof TenantAdminRouteWithChildren
  '/_tenant/login': typeof TenantLoginRoute
  '/_central/': typeof CentralIndexRoute
  '/_tenant/admin/dashboard': typeof TenantAdminDashboardRoute
  '/_tenant/admin/orders': typeof TenantAdminOrdersRoute
  '/_tenant/admin/restaurants': typeof TenantAdminRestaurantsRoute
  '/_tenant/admin/settings': typeof TenantAdminSettingsRoute
  '/_tenant/admin/staff': typeof TenantAdminStaffRoute
  '/_tenant/admin/tables': typeof TenantAdminTablesRoute
  '/_tenant/admin/menu/items': typeof TenantAdminMenuItemsRoute
  '/_tenant/admin/menu/': typeof TenantAdminMenuIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/login'
    | '/'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/restaurants'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/tables'
    | '/admin/menu/items'
    | '/admin/menu'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/login'
    | '/'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/restaurants'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/tables'
    | '/admin/menu/items'
    | '/admin/menu'
  id:
    | '__root__'
    | '/_central'
    | '/_tenant'
    | '/_tenant/admin'
    | '/_tenant/login'
    | '/_central/'
    | '/_tenant/admin/dashboard'
    | '/_tenant/admin/orders'
    | '/_tenant/admin/restaurants'
    | '/_tenant/admin/settings'
    | '/_tenant/admin/staff'
    | '/_tenant/admin/tables'
    | '/_tenant/admin/menu/items'
    | '/_tenant/admin/menu/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CentralRoute: typeof CentralRouteWithChildren
  TenantRoute: typeof TenantRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_tenant': {
      id: '/_tenant'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof TenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_central': {
      id: '/_central'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof CentralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_central/': {
      id: '/_central/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof CentralIndexRouteImport
      parentRoute: typeof CentralRoute
    }
    '/_tenant/login': {
      id: '/_tenant/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof TenantLoginRouteImport
      parentRoute: typeof TenantRoute
    }
    '/_tenant/admin': {
      id: '/_tenant/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof TenantAdminRouteImport
      parentRoute: typeof TenantRoute
    }
    '/_tenant/admin/tables': {
      id: '/_tenant/admin/tables'
      path: '/tables'
      fullPath: '/admin/tables'
      preLoaderRoute: typeof TenantAdminTablesRouteImport
      parentRoute: typeof TenantAdminRoute
    }
    '/_tenant/admin/staff': {
      id: '/_tenant/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof TenantAdminStaffRouteImport
      parentRoute: typeof TenantAdminRoute
    }
    '/_tenant/admin/settings': {
      id: '/_tenant/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof TenantAdminSettingsRouteImport
      parentRoute: typeof TenantAdminRoute
    }
    '/_tenant/admin/restaurants': {
      id: '/_tenant/admin/restaurants'
      path: '/restaurants'
      fullPath: '/admin/restaurants'
      preLoaderRoute: typeof TenantAdminRestaurantsRouteImport
      parentRoute: typeof TenantAdminRoute
    }
    '/_tenant/admin/orders': {
      id: '/_tenant/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof TenantAdminOrdersRouteImport
      parentRoute: typeof TenantAdminRoute
    }
    '/_tenant/admin/dashboard': {
      id: '/_tenant/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof TenantAdminDashboardRouteImport
      parentRoute: typeof TenantAdminRoute
    }
    '/_tenant/admin/menu/': {
      id: '/_tenant/admin/menu/'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof TenantAdminMenuIndexRouteImport
      parentRoute: typeof TenantAdminRoute
    }
    '/_tenant/admin/menu/items': {
      id: '/_tenant/admin/menu/items'
      path: '/menu/items'
      fullPath: '/admin/menu/items'
      preLoaderRoute: typeof TenantAdminMenuItemsRouteImport
      parentRoute: typeof TenantAdminRoute
    }
  }
}

interface CentralRouteChildren {
  CentralIndexRoute: typeof CentralIndexRoute
}

const CentralRouteChildren: CentralRouteChildren = {
  CentralIndexRoute: CentralIndexRoute,
}

const CentralRouteWithChildren =
  CentralRoute._addFileChildren(CentralRouteChildren)

interface TenantAdminRouteChildren {
  TenantAdminDashboardRoute: typeof TenantAdminDashboardRoute
  TenantAdminOrdersRoute: typeof TenantAdminOrdersRoute
  TenantAdminRestaurantsRoute: typeof TenantAdminRestaurantsRoute
  TenantAdminSettingsRoute: typeof TenantAdminSettingsRoute
  TenantAdminStaffRoute: typeof TenantAdminStaffRoute
  TenantAdminTablesRoute: typeof TenantAdminTablesRoute
  TenantAdminMenuItemsRoute: typeof TenantAdminMenuItemsRoute
  TenantAdminMenuIndexRoute: typeof TenantAdminMenuIndexRoute
}

const TenantAdminRouteChildren: TenantAdminRouteChildren = {
  TenantAdminDashboardRoute: TenantAdminDashboardRoute,
  TenantAdminOrdersRoute: TenantAdminOrdersRoute,
  TenantAdminRestaurantsRoute: TenantAdminRestaurantsRoute,
  TenantAdminSettingsRoute: TenantAdminSettingsRoute,
  TenantAdminStaffRoute: TenantAdminStaffRoute,
  TenantAdminTablesRoute: TenantAdminTablesRoute,
  TenantAdminMenuItemsRoute: TenantAdminMenuItemsRoute,
  TenantAdminMenuIndexRoute: TenantAdminMenuIndexRoute,
}

const TenantAdminRouteWithChildren = TenantAdminRoute._addFileChildren(
  TenantAdminRouteChildren,
)

interface TenantRouteChildren {
  TenantAdminRoute: typeof TenantAdminRouteWithChildren
  TenantLoginRoute: typeof TenantLoginRoute
}

const TenantRouteChildren: TenantRouteChildren = {
  TenantAdminRoute: TenantAdminRouteWithChildren,
  TenantLoginRoute: TenantLoginRoute,
}

const TenantRouteWithChildren =
  TenantRoute._addFileChildren(TenantRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  CentralRoute: CentralRouteWithChildren,
  TenantRoute: TenantRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
