/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TenantRouteImport } from './routes/_tenant'
import { Route as CentralRouteImport } from './routes/_central'
import { Route as CentralIndexRouteImport } from './routes/_central/index'
import { Route as TenantLoginRouteImport } from './routes/_tenant/login'

const TenantRoute = TenantRouteImport.update({
  id: '/_tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralRoute = CentralRouteImport.update({
  id: '/_central',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralIndexRoute = CentralIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CentralRoute,
} as any)
const TenantLoginRoute = TenantLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => TenantRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof TenantLoginRoute
  '/': typeof CentralIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof TenantLoginRoute
  '/': typeof CentralIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_central': typeof CentralRouteWithChildren
  '/_tenant': typeof TenantRouteWithChildren
  '/_tenant/login': typeof TenantLoginRoute
  '/_central/': typeof CentralIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/'
  id: '__root__' | '/_central' | '/_tenant' | '/_tenant/login' | '/_central/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CentralRoute: typeof CentralRouteWithChildren
  TenantRoute: typeof TenantRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_tenant': {
      id: '/_tenant'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof TenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_central': {
      id: '/_central'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof CentralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_central/': {
      id: '/_central/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof CentralIndexRouteImport
      parentRoute: typeof CentralRoute
    }
    '/_tenant/login': {
      id: '/_tenant/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof TenantLoginRouteImport
      parentRoute: typeof TenantRoute
    }
  }
}

interface CentralRouteChildren {
  CentralIndexRoute: typeof CentralIndexRoute
}

const CentralRouteChildren: CentralRouteChildren = {
  CentralIndexRoute: CentralIndexRoute,
}

const CentralRouteWithChildren =
  CentralRoute._addFileChildren(CentralRouteChildren)

interface TenantRouteChildren {
  TenantLoginRoute: typeof TenantLoginRoute
}

const TenantRouteChildren: TenantRouteChildren = {
  TenantLoginRoute: TenantLoginRoute,
}

const TenantRouteWithChildren =
  TenantRoute._addFileChildren(TenantRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  CentralRoute: CentralRouteWithChildren,
  TenantRoute: TenantRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
